name: OpenShift

env:
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: ""  # Optional, specify if needed
  APP_NAME: arumporul
  APP_PORT: ""  # Optional, specify if needed
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_REGISTRY_USER: ${{ github.actor }}
  IMAGE_REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_TAGS: ""  # Optional, specify if needed

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ env.IMAGE_REGISTRY }}/${{ env.APP_NAME }}:${{ github.sha }} .
        docker push ${{ env.IMAGE_REGISTRY }}/${{ env.APP_NAME }}:${{ github.sha }}

    - name: Log in to OpenShift
      uses: redhat-actions/oc-login@v1
      with:
        server: ${{ env.OPENSHIFT_SERVER }}
        token: ${{ env.OPENSHIFT_TOKEN }}
        namespace: ${{ env.OPENSHIFT_NAMESPACE }}

    - name: Deploy to OpenShift
      run: |
        oc new-app ${{ env.IMAGE_REGISTRY }}/${{ env.APP_NAME }}:${{ github.sha }} --name=${{ env.APP_NAME }} --port=${{ env.APP_PORT }}

    - name: Expose OpenShift app
      run: |
        oc expose svc/${{ env.APP_NAME }}
